name: "Build APK"

on: push

jobs:
  BuildApk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2

      - name: build apk
        run: flutter build apk --release
      
      - name: Upload APK File
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: ./build/app/outputs/flutter-apk/app-release.apk